### PR TITLE
Adding in password functionality

### PR DESCRIPTION
**Pull request by hackervera**
This allows one to create a secure 'website password' and add the public key to their site as a data uri.

The IndieAuth provider will ask for this 'website password' and create a signature in the browser. Browser then sends signature to backend for verification

How to create website password with sodium [included via cdn] 
`sodium.to_hex(sodium.crypto_sign_seed_keypair(sodium.crypto_generichash(32, "YOURPASSWORD")).publicKey)`

You then add this to website as
`<link rel="password" href="data:text/plain,YOURPUBLICKEY">`

Public key is a 64 character hex string (32 byte)

### CODE REVIEW

**Comment by aaronpk** [comment]
Well this is really interesting! 

Is there any precedent for linking to a sodium public key from a website? I'd like to use an existing rel value for that if possible. For example, PGP uses `rel=pgpkey`.

Alternately, is there a media type for the sodium key that could be used in place of `data:text/plain`, which would mean we could use the generic `rel=publickey`?

**Comment by aaronpk** [comment]
Preview of what this looks like in the browser:

password

If I'm reading this right, what's actually happening is you're signing a string representation of the current date in the browser, and then on the server side, the server verifies the signature against the public key and checks if the date is within 15 seconds of now?

**Comment by tjgillies** [comment]
I haven't seen a rel value yet, but I can do a search. I'm using a data uri because the key is so short there is no point in creating a link somewhere else like the monstrosity that is pgp. 25519 keys in general are pretty new so I doubt there is any existing web standard to use them in this manner (Not that I could find at least). I'll keep my eyes open for use cases.

Regarding the 15 second signature. Yeah I am essentially using it as a nonce to prevent replay attacks.

**Comment by aaronpk** [comment]
I was thinking something like `href="data:text/ec25519,YOURPUBLICKEY"` so that there's some indication of the elliptic curve it uses, in case you want to use a different one later or publish multiple.

Are there other uses for publishing the public key? If so, that's another reason to not use `rel=password`. It makes more sense to use a rel value describing the thing, rather than describing the use of it.

**Comment by tjgillies** [comment]
Ah yeah good point, also it would be `/ed25519` since it's a signature key. Maybe just rel=ed25519 since that's really the only part of a key you would publish it would be obvious it's a public key.

One thing though. I kinda think it's a bad idea to reuse this key. I created something that's easily disposable because of the security implications. If your key is compromised by a rogue auth endpoint I don't want to risk compromising any other identities.

**Pull request closed without merging**
